version: "3"

services:
  demo_db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE: demo_db_mysql8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - sticky_volume:/var/lib/mysql
      - ./config/:/docker-entrypoint-initdb.d/

volumes:
  sticky_volume:
