server.port: 8080

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/demo_master_mysql8?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 300
      connectionTimeout: 30_000
      idleTimeout: 600_000
      maxLifetime: 1_800_000
      leak-detection-threshold: 2_000

  jpa:
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration # default
